# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tiket.ui'
#
# Created: Fri Jun 02 14:32:06 2017
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(895, 563)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(313, 34, 54, 12))
        self.label_6.setObjectName("label_6")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(54, 67, 71, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(230, 30, 71, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_3.setGeometry(QtCore.QRect(120, 68, 71, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_5 = QtWidgets.QCheckBox(Form)
        self.checkBox_5.setGeometry(QtCore.QRect(190, 68, 71, 16))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_7 = QtWidgets.QCheckBox(Form)
        self.checkBox_7.setGeometry(QtCore.QRect(330, 68, 71, 16))
        self.checkBox_7.setObjectName("checkBox_7")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(54, 34, 54, 12))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(184, 34, 54, 12))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(493, 34, 54, 12))
        self.label_7.setObjectName("label_7")
        self.timeEdit = QtWidgets.QTimeEdit(Form)
        self.timeEdit.setGeometry(QtCore.QRect(553, 30, 118, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.checkBox_4 = QtWidgets.QCheckBox(Form)
        self.checkBox_4.setGeometry(QtCore.QRect(260, 69, 71, 16))
        self.checkBox_4.setObjectName("checkBox_4")
        self.dateEdit_2 = QtWidgets.QDateEdit(Form)
        self.dateEdit_2.setGeometry(QtCore.QRect(373, 30, 110, 22))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(682, 33, 121, 16))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 65, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(100, 30, 71, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(50, 110, 791, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(12)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        self.allSelect = QtWidgets.QPushButton(Form)
        self.allSelect.setGeometry(QtCore.QRect(50, 370, 81, 23))
        self.allSelect.setObjectName("allSelect")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(60, 400, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(170, 400, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(290, 400, 61, 16))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(430, 470, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.selectTicketInfo = QtWidgets.QTableWidget(Form)
        self.selectTicketInfo.setGeometry(QtCore.QRect(50, 420, 91, 121))
        self.selectTicketInfo.setObjectName("selectTicketInfo")

        self.peopleInfo = QtWidgets.QTableWidget(Form)
        self.peopleInfo.setGeometry(QtCore.QRect(170, 420, 91, 121))
        self.peopleInfo.setObjectName("peopleInfo")
        self.setInfo = QtWidgets.QTableWidget(Form)
        self.setInfo.setGeometry(QtCore.QRect(290, 420, 91, 121))
        self.setInfo.setObjectName("setInfo")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "出发日期："))
        self.checkBox_2.setText(_translate("Form", "G-高铁"))
        self.checkBox_3.setText(_translate("Form", "D-动车"))
        self.checkBox_5.setText(_translate("Form", "Z-直达"))
        self.checkBox_7.setText(_translate("Form", "K-快速"))
        self.label.setText(_translate("Form", "出发地："))
        self.label_5.setText(_translate("Form", "目的地："))
        self.label_7.setText(_translate("Form", "出发时间："))
        self.checkBox_4.setText(_translate("Form", "T-特快"))
        self.checkBox.setText(_translate("Form", "仅显示可预订车次"))
        self.pushButton_2.setText(_translate("Form", "查询"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "车次"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "出发站"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "到达站"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "历时"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "商务座"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "特等座"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "一等座"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "二等座"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "软卧"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Form", "硬卧"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Form", "软座"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("Form", "无座"))
        self.allSelect.setText(_translate("Form", "全部选中"))
        self.label_2.setText(_translate("Form", "*所选车次:"))
        self.label_3.setText(_translate("Form", "*选择乘客:"))
        self.label_4.setText(_translate("Form", "*选择坐席:"))
        self.pushButton.setText(_translate("Form", "完成设置"))

